# Generated by Django 3.2.6 on 2021-09-04 16:34
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('slug',)},
        ),
    ]
