# Generated by Django 3.2.6 on 2021-09-04 16:49
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_store_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={},
        ),
    ]
