# Generated by Django 3.2.6 on 2021-09-04 16:47
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_lookup', '0006_rename_title_class_storeselectors_image_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={},
        ),
    ]
